_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 20
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
DATASETS:
  TRAIN: ("train_dataset",)
  TEST: ("test_dataset",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 12500
  CHECKPOINT_PERIOD: 200